### PR TITLE
[Fix] Fix SyncBN build in PyTorch 1.9

### LINKED ISSUE #1137: SyncBatchNorm breaks after PyTorch 1.9.0
**Describe the Issue**
`torch.nn.SyncBatchNorm` has been updated since PyTorch 1.9.0 and `_specify_ddp_gpu_num()` is no longer available, breaking the following code snippet: https://github.com/open-mmlab/mmcv/blob/eb08835fa246ea81263eb25fbe2caa54ef11271c/mmcv/utils/parrots_wrapper.py#L83-L87

More details: https://github.com/open-mmlab/mmocr/issues/325

### PR DESCRIPTION
**Pull request by xvjiarui**
## Motivation

Fix #1137 

## Modification

Check whether attribute `_specify_ddp_gpu_num` exists. 

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?

No

### CODE REVIEW

**Comment by xvjiarui** [comment]
We may need CI for PyTorch 1.9. @zhouzaida

**Comment by zhouzaida** [comment]
yet, we are resolving the compatibility in PyTorch1.9

**Comment by ZwwWayne** [comment]
Seems this PR does not totally fix #1137 here :https://github.com/open-mmlab/mmcv/blob/eb08835fa246ea81263eb25fbe2caa54ef11271c/mmcv/utils/parrots_wrapper.py#L83-L87

**Comment by zhouzaida** [comment]
We should check why pytorch1.9 removes the function, please refer to [Remove _specify_ddp_gpu_num method](https://github.com/pytorch/pytorch/pull/56425)

**Comment by xvjiarui** [comment]
> We should check why pytorch1.9 removes the function, please refer to [Remove _specify_ddp_gpu_num method](https://github.com/pytorch/pytorch/pull/56425)

They remove it because it's not useful any more. The attribute `_ddp_gpu_size` is also removed.

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
