### PR TITLE
Added Weight and Biases logger.

### PR DESCRIPTION
**Pull request by ternaus**

### CODE REVIEW

**Comment by ternaus** [comment]
It is a bit unclear to me how to write tests for W&B logger.

@vanpelt could you please give a hint?

**Comment by hellock** [comment]
Awesome! Does it work with the W&B service now?

**Comment by vanpelt** [comment]
@hellock yep, this should be good to go!  Only issue is a flake8 error in the test.  @ternaus can you fix that?

**Comment by hellock** [comment]
requirements.txt has been removed and `mock` may be added [here](https://github.com/open-mmlab/mmcv/blob/master/.travis.yml#L11) since it is only required for testing.

**Pull request merged**
