### PR TITLE
Add type hints for mmcv/engine/test.py

### PR DESCRIPTION
**Pull request by tcexeexe**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Modification

follow the #2025 
Add type hints for mmcv/engine/test.py

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by zhouzaida** [comment]
Hi, the lint failed. https://app.circleci.com/pipelines/github/open-mmlab/mmcv/976/workflows/946a26dd-6edc-4f04-9640-06e17391ec60/jobs/1836

**Comment by zhouzaida** [comment]
> > Hi, the lint failed. https://app.circleci.com/pipelines/github/open-mmlab/mmcv/976/workflows/946a26dd-6edc-4f04-9640-06e17391ec60/jobs/1836
> > @[zhouzaida](https://github.com/zhouzaida)
> > Hello, l have no idea about the error in 137,146,159. Could you give me some advice about it ,thanks a lot!
> 
> 4149862dd99ddee9881c5d16db97003

Hi, I did a commit and you can see the difference with your commits.

**Review by zhouzaida — APPROVED** [review]

**Review by HAOCHENYE — APPROVED** [review]

**Comment by tcexeexe** [comment]
> > > Hi, the lint failed. https://app.circleci.com/pipelines/github/open-mmlab/mmcv/976/workflows/946a26dd-6edc-4f04-9640-06e17391ec60/jobs/1836
> > > @[zhouzaida](https://github.com/zhouzaida)
> > > Hello, l have no idea about the error in 137,146,159. Could you give me some advice about it ,thanks a lot!
> > 
> > 
> > 4149862dd99ddee9881c5d16db97003
> 
> Hi, I did a commit and you can see the difference with your commits.

Thanks a lot!

**Comment by tcexeexe** [comment]
> > > Hi, the lint failed. https://app.circleci.com/pipelines/github/open-mmlab/mmcv/976/workflows/946a26dd-6edc-4f04-9640-06e17391ec60/jobs/1836
> > > @[zhouzaida](https://github.com/zhouzaida)
> > > Hello, l have no idea about the error in 137,146,159. Could you give me some advice about it ,thanks a lot!
> > 
> > 
> > 4149862dd99ddee9881c5d16db97003
> 
> Hi, I did a commit and you can see the difference with your commits.

Thanks a lot! I will imitate it

**Comment by tcexeexe** [comment]
> > > Hi, the lint failed. https://app.circleci.com/pipelines/github/open-mmlab/mmcv/976/workflows/946a26dd-6edc-4f04-9640-06e17391ec60/jobs/1836
> > > @[zhouzaida](https://github.com/zhouzaida)
> > > Hello, l have no idea about the error in 137,146,159. Could you give me some advice about it ,thanks a lot!
> > 
> > 
> > 4149862dd99ddee9881c5d16db97003
> 
> Hi, I did a commit and you can see the difference with your commits.
@zhouzaida 
Hello~ 
l have read your commit carefully ,and may I ask the difference between 
```
part_file = osp.join(tmpdir, f'part_{rank}.pkl')  # type: ignore
    mmcv.dump(result_part, part_file) 
```
and 
`mmcv.dump(result_part, osp.join(tmpdir, f'part_{rank}.pkl'))`
l think they are do the same job.

**Comment by zhouzaida** [comment]
Because the type hint of `tmpdir` can be None but `osp.join` does not accept None. And then mypy raised an error. 

As a workaround, I added `# type: ignore` to ignore this error raised by mypy.

**Pull request merged**
