### PR TITLE
[Fix]: Fix optimizer 'ValueError' when using PReLU activation.

### PR DESCRIPTION
**Pull request by KeiChiTse**
## Motivation

When using parameterized activation like PReLU in FFN, current way of initializing activation functions will cause a 'ValueError' in optimizer.
i.e. `ValueError: some parameters appear in more than one parameter group`

## Modification

Call 'build_activation_layer' function repeatedly instead of using 'self.activate' multiple times.

### CODE REVIEW

**Comment by zhouzaida** [comment]
> [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2444) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2444) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2444) it.

Hi, thanks for your contribution. Please sign the CLA before we merge this PR.

**Comment by KeiChiTse** [comment]
> > [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2444) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2444) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2444) it.
> 
> Hi, thanks for your contribution. Please sign the CLA before we merge this PR.

Hi! I've signed the CLA license already!

**Comment by zhouzaida** [comment]
Hi, the lint failed and you can merge the upstream 2.x to fix the error.

**Comment by KeiChiTse** [comment]
> Hi, the lint failed and you can merge the upstream 2.x to fix the error.

图片
Hi! I wonder how can I fix this **mypy** hook error?

**Comment by zhouzaida** [comment]
Hi, you can use the following commands to fix the mypy error.

```bash
git remote add open-mmlab git@github.com:open-mmlab/mmcv.git
git pull open-mmlab 2.x
```

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
