### PR TITLE
Fixed fp16_optimizer state bug

### PR DESCRIPTION
**Pull request by wdmwhh**

### CODE REVIEW

**Comment by yhcao6** [comment]
Can you give an example where the bug will happen?

**Comment by wdmwhh** [comment]
> Can you give an example where the bug will happen?

When one trains the model resumed from a checkpoint in fp16 setting. 
https://github.com/open-mmlab/mmcv/issues/577

**Comment by yhcao6** [comment]
It seems #566 is related to this Pr, could you have a check that?

**Comment by wdmwhh** [comment]
> It seems #566 is related to this Pr, could you have a check that?

Yes,  they are related. Both the changes are able to fix the bug.

**Comment by shinya7y** [comment]
Which implementation is better in terms of memory consumption?

**Comment by yhcao6** [comment]
Thanks for your contribution. Could you fix the lint error?

**Review by yhcao6 — APPROVED** [review]
Will fix lint after merge

**Pull request merged**
