### PR TITLE
[Docs] Fix the example error in registry.md

### PR DESCRIPTION
**Pull request by PungTeng**
def converter2(a, b):
    return Converter1(a, b)

### CODE REVIEW

**Review by zhouzaida — APPROVED** [review]

**Comment by zhouzaida** [comment]
> [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2243) it.

Hi @PungTeng , thanks for you contribution. Before we merge this PR, you need to sign the CLA.

**Comment by PungTeng** [comment]
> > [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2243) it.
> 
> Hi @PungTeng , thanks for you contribution. Before we merge this PR, you need to sign the CLA.

Okay，I have agreed to the CLA for open-mmlab/mmcv. Thanks!

**Comment by PungTeng** [comment]
> > [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2243) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2243) it.
> 
> Hi @PungTeng , thanks for you contribution. Before we merge this PR, you need to sign the CLA.

Okay@zhouzaida，I have agreed to the CLA for open-mmlab/mmcv. Thanks!

**Comment by OpenMMLab-Miao** [comment]
Hi @PungTeng ！First of all, we want to express our gratitude for your significant PR in the MMCV project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
