### PR TITLE
[Feature] Support DeformRoiPool with cambricon MLU backend

### PR DESCRIPTION
**Pull request by defei-coder**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

The motivation of the PR is to support running DeformRoiPool with Cambricon MLU backend.

It includes three parts:

    1. Add deform_roi_pool_mlu_kernel.mlu src code as MLU kernel.
    2. Add deform_roi_pool_mlu.cpp to support launching kernel in PyTorch.
    3. Refactor test_deform_roi_pool.py to support testing DeformRoiPool with MLU backend.

## Modification

- MLU src code
  Add MLU src code of DeformRoiPool in directory mmcv/ops/csrc/common/mlu/deform_roi_pool_mlu_kernel.mlu.
- PyTorch adaptation
  Adapt DeformRoiPool for PyTorch in mmcv/ops/csrc/pytorch/mlu/deform_roi_pool_mlu.cpp.
- Unit test
  Surpport test DeformRoiPool with various backends in tests/test_ops/test_deform_roi_pool.py.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by grimoire — COMMENTED** [review]
Failed with:

```
./mmcv/ops/csrc/common/mlu/deform_roi_pool_mlu_kernel.mlu:132:26: error: no matching function for call to 'max'
          static_cast<T>(std::max(roi_bin_grid_height * roi_bin_grid_width, 1));
```

**Comment by defei-coder** [comment]
@grimoire Hi, I build mmcv successfully. How do you build？What is your build environment？Such as pytorch version and neuware_home version(in virtual environment pytorch folder neuware_home/version.txt)

**Comment by defei-coder** [comment]
@grimoire  hi, I remove the use of std libaray, you can rebuild mmcv.

**Comment by grimoire** [comment]
Compile passed. Unit test failed with log:
```
RuntimeError: offset should be 4d tensor, got 4D.
E       Exception raised from DeformRoIPoolForwardMLUKernelLauncher at ./mmcv/ops/csrc/pytorch/mlu/deform_roi_pool_mlu.cpp:71 (most recent call first):
```

- Neuware Version 2.8.5
- pytorch==1.9.0
- torch-mlu==1.3.2-torch1.9

**Comment by defei-coder** [comment]
@grimoire hi, the error information in my code is wrong, I just fixed it. You can rebuild mmcv and test again. According to your error information, I think the dim of offset tensor is wrong.

**Comment by grimoire** [comment]
failed with new logs:

```python
RuntimeError: offset should be 4d tensor, got 1D.
```

**Comment by defei-coder** [comment]
> failed with new logs:
> 
> ```python
> RuntimeError: offset should be 4d tensor, got 1D.
> ```

@grimoire  Is the test code used provided by test_deform_roi_pool_allclose in [test_deform_roi_pool.py](https://github.com/defei-coder/mmcv/blob/deform_roi_pool_mlu/tests/test_ops/test_deform_roi_pool.py)? The offset is created in DeformRoIPoolPack by input tensor. I have tested the test code is ok locally. Maybe you can print the input tensor information.

**Comment by grimoire** [comment]
the test passed after [1e998ac](https://github.com/open-mmlab/mmcv/pull/2137/commits/1e998accdcfa73baa945df4b6f889ebbfc90a6bd), did `.mlu()` and `.to(device)` have different behavior?

**Comment by defei-coder** [comment]
> the test passed after [1e998ac](https://github.com/open-mmlab/mmcv/pull/2137/commits/1e998accdcfa73baa945df4b6f889ebbfc90a6bd), did `.mlu()` and `.to(device)` have different behavior?

Hi, @grimoire. I find the reason for failure. Due to I used `offset.data_ptr()`, when `offset = input.new_zeros(0)`, this operator may be uncertainty. Not related to `.mlu()` or `.to(device)`. You can rebuild mmcv and test it. Sorry for my fault!

**Review by grimoire — APPROVED** [review]
Works now! LGTM

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
