### PR TITLE
[Feature] Support RoiPool with Cambricon MLU backend

### PR DESCRIPTION
**Pull request by zcyKTH**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

The motivation of the PR is to support running RoiPool with Cambricon MLU backend.

It includes three parts:

1. Add `roi_pool_mlu_kernel.mlu` src code as MLU kernel.
2. Add `roi_pool_mlu.cpp` to support launching kernel in PyTorch.
3. Refactor `test_roi_pool.py` to support testing RoiPool with MLU backend.

## Modification

* MLU src code
Add MLU src code of RoiPool in directory `mmcv/ops/csrc/common/mlu/roi_pool_mlu_kernel.mlu`.
* PyTorch adaptation
Adapt RoiPool for PyTorch in `mmcv/ops/csrc/pytorch/mlu/roi_pool_mlu.cpp`.
* Common functions
Add data conversion functions between fp32 and int32 in `mmcv/ops/csrc/common/mlu/common_mlu_helper.hpp`.
* Unit test
Surpport test RoiPool with various backends in `tests/test_ops/test_roi_pool.py`.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by zhouzaida** [comment]
Please update https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/ops.md and https://github.com/open-mmlab/mmcv/blob/master/docs/zh_cn/understand_mmcv/ops.md

**Comment by zcyKTH** [comment]
> Please update https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/ops.md and https://github.com/open-mmlab/mmcv/blob/master/docs/zh_cn/understand_mmcv/ops.md

Done

**Comment by grimoire** [comment]
@zcyKTH  How can I check the version?

**Comment by zcyKTH** [comment]
> @zcyKTH How can I check the version?

Try to check `version.txt` in `$NEUWARE_HOME` directory.

**Comment by grimoire** [comment]
Neuware Version 2.6.4 

The warning appears when compiling the op. The build finished with no error and the test also passed.
Can we ignore the warning?

**Comment by zcyKTH** [comment]
> Neuware Version 2.6.4
> 
> The warning appears when compiling the op. The build finished with no error and the test also passed. Can we ignore the warning?

Yep. Just ignore these oversensitive warnings and they have been removed in future Neuware Version.

**Review by grimoire — APPROVED** [review]
LGTM

**Pull request merged**
