### PR TITLE
Add support of TorchVision's Model Registration API on MMCV

### PR DESCRIPTION
**Pull request by datumbox**
Hi OpenMMLab team,

First of all thank you very much for developing your awesome framework.

TorchVision has recently introduced a new [Model Registration API](https://pytorch.org/blog/easily-list-and-initialize-models-with-new-apis-in-torchvision/) which allows the easier listing of models and weights. Its aim is to eliminate the somehow hacky idiom of using `torchvision.models.__dict__` to retrieve models and weights.

In this PR, I'm updating your existing implementation introduced at https://github.com/open-mmlab/mmcv/issues/1848 to use our new API. Please note that I'm going for the minimum number of modifications necessary; the code may be further simplified but that might require additional discussion.

For full transparency, the new API is currently considered Beta. We've intentionally marked it as such to ensure that we can act upon the feedback of our partners and users. We are currently collecting feedback at https://github.com/pytorch/vision/issues/6365 and hoping to promote to stable before TorchVision v0.14. If you have any feedback or feature requests, we would be happy to discuss more. Finally, please note that if we end up making breaking changes on the API after you merge this PR, we will make sure to follow up with all the necessary fixes to keep the Open-MMLab users unaffected.

Looking forward to your feedback.

### CODE REVIEW

**Comment by zhouzaida** [comment]
> [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2246) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2246) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2246) it.

Hi @datumbox , thanks to the TorchVision team for keeping us informed of new changes. Totally agree with the Model Registration API to make it easier to get models and weights. After signing the CLA, we can merge this PR.

**Review by zhouzaida — APPROVED** [review]

**Comment by datumbox** [comment]
@zhouzaida Thank you very much for the prompt review. I really appreciate it.

I've raised a request to my company to approve my signing of the CLAs. It's likely to take a week but I don't believe this is going to be an issue. I opted for going through the whole approval process to be able to make more contributions to your project on the future if necessary. :)

I'll ping you once I get the approval and sign the CLAs.

**Comment by zhouzaida** [comment]
> @zhouzaida Thank you very much for the prompt review. I really appreciate it.
> 
> I've raised a request to my company to approve my signing of the CLAs. It's likely to take a week but I don't believe this is going to be an issue. I opted for going through the whole approval process to be able to make more contributions to your project on the future if necessary. :)
> 
> I'll ping you once I get the approval and sign the CLAs.

Okay, looking forward to our more cooperation.

**Comment by datumbox** [comment]
@zhouzaida I got permission to sign the CLAs. We should be good to go :)

Let me know if you need anything else from my side. Thanks!

**Review by HAOCHENYE — APPROVED** [review]

**Pull request merged**
