### PR TITLE
add vit_large_patch16_384 pretrain

### PR DESCRIPTION
**Pull request by RockeyCoss**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

add vit_large_patch16_384 pretrain to mmcv

## Modification

add vit_large_patch16_384 pretrain to mmcv

### CODE REVIEW

**Review by zhouzaida — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Involve @mzr1996 to take a look

**Comment by mzr1996** [comment]
Do you mean these models?
https://github.com/open-mmlab/mmclassification/tree/master/configs/vision_transformer#imagenet-1k

**Comment by RockeyCoss** [comment]
> Do you mean these models? https://github.com/open-mmlab/mmclassification/tree/master/configs/vision_transformer#imagenet-1k

Nope，our pretrain is converted from [here](https://github.com/rwightman/pytorch-image-models/releases/download/v0.1-vitjx/jx_vit_large_p16_384-b3be5167.pth)(from repository pytorch-image-models), while mmclassification's is converted from model zoo of Google Research.

**Comment by mzr1996** [comment]
> 

Well, the checkpoints in [timm is also converted from Google Research](https://github.com/rwightman/pytorch-image-models/blob/1f53db2eceecfc38032ebdf2ff31db3188ff615d/timm/models/vision_transformer.py#L54-L55), isn't it?

**Comment by RockeyCoss** [comment]
> > 
> 
> Well, the checkpoints in [timm are also converted from Google Research](https://github.com/rwightman/pytorch-image-models/blob/1f53db2eceecfc38032ebdf2ff31db3188ff615d/timm/models/vision_transformer.py#L54-L55), isn't it?

I checked their values and I found that they are not the same.
For example, 
for key layers.23.ffn.layers.1.bias

The ViT-L16* in Pretrain model:
图片

The ViT-L16* in Finetune model:
图片

Our pretrain vit_large_patch16_384:
图片

**Comment by mzr1996** [comment]
> Involve @mzr1996 to take a look

Ok, the checkpoints in mmcls are converted from Google Research's new checkpoints which have higher performance.
But mmseg needs the old checkpoints in timm to align some results.

**Comment by ZwwWayne** [comment]
Since https://github.com/open-mmlab/mmcv/pull/1513 has been merged. Is this PR still necessary?

**Comment by RockeyCoss** [comment]
> Since #1513 has been merged. Is this PR still necessary?

well, we will retrain the baseline with the new pretrain in the future. However, since our current benchmark is based on the old pretrain(And the new benchmark trained with the new pretrain will not cover the old benchmark), I think it's still necessary to merge this pr. Otherwise the users can't download the pretrain file from mmcv.

**Comment by zhouzaida** [comment]
Downstream repos should use the pre-trained checkpoints from mmcls.

**Pull request closed without merging**
