### PR TITLE
[Fix] Fix floor/ceil error in deform_attn for windows 

### PR DESCRIPTION
**Pull request by 007gzs**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation
Help user to build mmcv in windows

## Modification
1. add windows sdk setting to doc
2. fix error in vs2019
```
#ifdef _WIN32
#define ___floor floor
#define floor(x) ___floor((double)(x))
#define ___ceil ceil
#define ceil(x) ___ceil((double)(x))
#endif
```

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Comment by fcakyon** [comment]
current mmcv version (1.3.4) gives error on windows 10, cuda 11, rtx 3060, vs 2019 (16.8.6-16.9.5). @007gzs does this pr fix it?

**Comment by 007gzs** [comment]
> current mmcv version (1.3.4) gives error on windows 10, cuda 11, rtx 3060, vs 2019 (16.8.6-16.9.5). @007gzs does this pr fix it?

i build ok by this pr. my system info windows 10 + cuda11.2+ vs2019(16.9.4) + win10sdk 10.0.19041.0

**Comment by ZwwWayne** [comment]
Hi @007gzs ,
Thanks for your PR. There is another thing that we seek for your help. It seems that you have uploaded the `openmim` package to PyPI, which makes our automatic build & deployment of `openmim` failed. To make the publishing process of `openmim` python package back to normal, could you please go to `Your project` page in PyPi and add `open-mmlab` as the owner of the project?

**Comment by 007gzs** [comment]
> Hi @007gzs ,
> Thanks for your PR. There is another thing that we seek for your help. It seems that you have uploaded the `openmim` package to PyPI, which makes our automatic build & deployment of `openmim` failed. To make the publishing process of `openmim` python package back to normal, could you please go to `Your project` page in PyPi and add `openmmlab` as the owner of the project?

@ZwwWayne i have added please try again

**Comment by wangruohui** [comment]
Thank you for help, but I have a question. Why do we need to convert x to double first? As this introduce additional overheads.

And following previous solution, Does a direct call on floorf(x) solve the problem?
Moreover, if yes, additional include and lib path may be redundant.

**Comment by 007gzs** [comment]
> 谢谢你的帮助，但我有一个问题。为什么我们需要先将 x 转换为 double ？因为这会引入额外的开销。
> 
> 按照之前的解决方案（#891），直接调用 floorf(x) 是否可以解决问题？
> 此外，如果是，额外的 include 和 lib 路径可能是多余的。

I'm not sure if x in floor (x) will exceed the float range.

If it is confirmed that it will not exceed, it can be directly changed to floorf

**Comment by wangruohui** [comment]
I think no, because here floor and ceil is usually applied on image size, which would be much smaller than the maximum limit of float (which is 3e38). And previous modification introduce no problem till now, so I think replace to `floorf` and `ceilf` from `floor` and `ceil` is a better solution. 

> I'm not sure if x in floor (x) will exceed the float range.
> 
> If it is confirmed that it will not exceed, it can be directly changed to floorf

**Comment by 007gzs** [comment]
change floor/ceil to floorf/ceilf

**Comment by fcakyon** [comment]
@wangruohui can we merge this pr?

**Review by wangruohui — APPROVED** [review]
lgtm

**Comment by wangruohui** [comment]
> @wangruohui can we merge this pr?

still need one reviewer to approve, then we can merge it.

**Comment by ZwwWayne** [comment]
Can be merged after fixing the lint issue.

**Review by jshilong — COMMENTED** [review]
LGTM

**Review by jshilong — APPROVED** [review]

**Comment by OpenMMLab-Coodinator** [comment]
Hi @007gzs ！First of all, we want to express our gratitude for your significant PR in this project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
