### PR TITLE
add max_keep_ckpts parameter

### PR DESCRIPTION
**Pull request by z-bingo**
add ``max_keep_ckpts'' parameter in checkpoint_config, only save the latest n models to save memory

### CODE REVIEW

**Comment by hellock** [comment]
Thanks for adding the feature. Please refer to the [contributing guide](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md#code-style) and fix the linting errors.

**Comment by z-bingo** [comment]
I have formatted the codes correctly, but `codecov/project` and `codecov/patch` are still cannot pass.

**Comment by hellock** [comment]
This is because the added code does not have corresponding unit tests. Currently we can ignore it.

**Comment by OpenMMLab-Assistant-007** [comment]
Hi!
@z-bingo 
First of all, we want to express our gratitude for your significant PR in the OpenMMLab project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
