### PR TITLE
Let progress goes to stderr

### PR DESCRIPTION
**Pull request by innerlee**
Fix https://github.com/open-mmlab/mmcv/issues/114

### CODE REVIEW

**Comment by hellock** [comment]
It is better to make it an argument of progress bar, like `file=sys.stdout`.

**Comment by innerlee** [comment]
Not sure why tests fail

**Comment by hellock** [comment]
> Not sure why tests fail

me too...

**Comment by innerlee** [comment]
Let's blame pytest https://github.com/pytest-dev/pytest/issues/1132

**Pull request merged**
