### PR TITLE
[Refactor] Refactor the interface for RoIAlignRotated

### PR DESCRIPTION
**Pull request by nijkah**
## Motivation

RoIAlignRotated does not have the same interface as RoIAlign.

## Modification

I edited its interface and added deprecated warning.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]

**Review by AllentDan — APPROVED** [review]

**Comment by zhouzaida** [comment]
Hi @nijkah , thanks for your contribution. LGTM. BTW, it would be better to add a unit test for the renaming behavior. https://github.com/open-mmlab/mmcv/blob/master/tests/test_ops/test_roi_align_rotated.py

**Comment by nijkah** [comment]
@zhouzaida Actually, I'm not familiar with a unit test. What is the best convention to test this kind of behavior?
Should I define new function like (def _test_roialign_rotated_deprecated_parameters) or just add new forward & backward with new & deprecated parameters under the functions _test_roialign_rotated_allclose?

**Comment by zhouzaida** [comment]
> @zhouzaida Actually, I'm not familiar with a unit test. What is the best convention to test this kind of behavior? Should I define new function like (def _test_roialign_rotated_deprecated_parameters) or just add new forward & backward with new & deprecated parameters under the function _test_roialign_rotated_allclose?

The former way may be better.

**Comment by nijkah** [comment]
@zhouzaida  Can you check the test code? Is the code you intended?

**Comment by nijkah** [comment]
@zhouzaida 
function _test_roialign_rotated_allclose tests the roi_align_rotated function not RoIAlignRotated Module.
Although function _test_roialign_rotated_gradcheck uses RoIAlignRotated Module, but it might seem odd to test deprecated parameters in that function.
Any suggestion? I am sorry to bother you. :(

**Comment by zhouzaida** [comment]
> @zhouzaida Function _test_roialign_rotated_allclose tests the roi_align_rotated function not RoIAlignRotated Module. Although function _test_roialign_rotated_gradcheck uses RoIAlignRotated Module, but it might seem odd to test deprecated parameters in that function. Any suggestion? I am sorry to bother you. :(

Yet, we just need to test deprecated parameters in `_test_roialign_rotated_allclose`.

**Comment by nijkah** [comment]
Option 1. Replace **roi_align_rotated function** with **RoIAlignRotated Module** in the _test_roialign_rotated_allclose.
Option 2. Just add a test code for **RoIAlignRotated Module** after for loop of _test_roialign_rotated_allclose.
like below
```
  for case, output in zip(inputs, outputs):
        np_input = np.array(case[0])
        np_rois = np.array(case[1])
        np_output = np.array(output[0])
        np_grad = np.array(output[1])
        x = torch.tensor(
            np_input, dtype=dtype, device=device, requires_grad=True)
        rois = torch.tensor(np_rois, dtype=dtype, device=device)
        output = roi_align_rotated(x, rois, (pool_h, pool_w), spatial_scale,
                                   sampling_ratio, True)
        output.backward(torch.ones_like(output))
        assert np.allclose(
            output.data.type(torch.float).cpu().numpy(), np_output, atol=1e-3)
        assert np.allclose(
            x.grad.data.type(torch.float).cpu().numpy(), np_grad, atol=1e-3)

        # end of original function

        roi_align_rotated_module_deprecated = RoIAlignRotated(
            out_size=(pool_h, pool_w),
            spatial_scale=spatial_scale,
            sample_num=sampling_ratio)

        output_v1 = roi_align_rotated_module_deprecated(x, rois)

        roi_align_rotated_module_new = RoIAlignRotated(
            output_size=(pool_h, pool_w),
            spatial_scale=spatial_scale,
            sampling_ratio=sampling_ratio)

        output_v2 = roi_align_rotated_module_new(x, rois)
        assert np.allclose(
            output_v1.data.type(torch.float).cpu().numpy(),
            output_v2.data.type(torch.float).cpu().numpy())
```

**Comment by zhouzaida** [comment]
> Option 1. Replace **roi_align_rotated function** with **RoIAlignRotated Module** in the _test_roialign_rotated_allclose. Option 2. Just add a test code for **RoIAlignRotated Module** after for loop of _test_roialign_rotated_allclose like below
> 
> ```
>   for case, output in zip(inputs, outputs):
>         np_input = np.array(case[0])
>         np_rois = np.array(case[1])
>         np_output = np.array(output[0])
>         np_grad = np.array(output[1])
>         x = torch.tensor(
>             np_input, dtype=dtype, device=device, requires_grad=True)
>         rois = torch.tensor(np_rois, dtype=dtype, device=device)
>         output = roi_align_rotated(x, rois, (pool_h, pool_w), spatial_scale,
>                                    sampling_ratio, True)
>         output.backward(torch.ones_like(output))
>         assert np.allclose(
>             output.data.type(torch.float).cpu().numpy(), np_output, atol=1e-3)
>         assert np.allclose(
>             x.grad.data.type(torch.float).cpu().numpy(), np_grad, atol=1e-3)
> 
>   # end of original function
> 
>   roi_align_rotated_module_deprecated = RoIAlignRotated(
>       out_size=(pool_h, pool_w),
>       spatial_scale=spatial_scale,
>       sample_num=sampling_ratio)
> 
>   output_v1 = roi_align_rotated_module_deprecated(x, rois)
> 
>   roi_align_rotated_module_new = RoIAlignRotated(
>       output_size=(pool_h, pool_w),
>       spatial_scale=spatial_scale,
>       sampling_ratio=sampling_ratio)
> 
>   output_v2 = roi_align_rotated_module_new(x, rois)
>   ssert np.allclose(
>             output_v1.data.type(torch.float).cpu().numpy(),
>             output_v2.data.type(torch.float).cpu().numpy())
> ```

Option2 would be fine.

**Review by zhouzaida — APPROVED** [review]

**Comment by nijkah** [comment]
Do you mean `forward` of `RoIAlignRotatedFunction` class? I think it is desirable to understand the interface.

**Comment by zhouzaida** [comment]
> @zhouzaida Do you mean `forward` of `RoIAlignRotatedFunction` class? I think it will be desirable to understand the interface. If you add emoji to this comment, I will edit it.

Got it. BTW, we also need to update the docstring.

**Comment by nijkah** [comment]
> > @zhouzaida Do you mean `forward` of `RoIAlignRotatedFunction` class? I think it will be desirable to understand the interface. If you add emoji to this comment, I will edit it.
> 
> Got it. BTW, we also need to update the docstring. image

I edited docstring.
And I also edited cuda and cpu interfaces to refactor the `RoIAlignRotatedFunction`.

**Comment by zhouzaida** [comment]
Please @luopeichao have a look.

**Comment by nijkah** [comment]
What should I do else for the next step? @zhouzaida

**Comment by zhouzaida** [comment]
> What should I do else for the next step? @zhouzaida

Thanks for your contribution. I will merge the PR in a few days.

**Comment by nijkah** [comment]
@zhouzaida 
Thanks for your reply. I apologize if I made you hurry. 😔
I just wished this PR will be merged soon since it makes mmdetection code for rotated objects messy.

**Comment by luopeichao** [comment]
Looks good to me about parrots extension changes.

**Review by luopeichao — APPROVED** [review]

**Comment by zhouzaida** [comment]
> @zhouzaida Thanks for your reply. I apologize if I made you hurry. 😔 I just wished this PR will be merged soon since it makes mmdetection code for rotated objects messy.

Thanks for your contribution.

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
