### PR TITLE
update c++17

### PR DESCRIPTION
**Pull request by grimoire**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

https://github.com/open-mmlab/mmcv/issues/2860

## Modification

comment constructor template of ShapeBase
c++14 -> c++17

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by grimoire** [comment]
Since cuda10 does not support c++17 and torch<=1.12 has cuda10.2 prebuild package, any environment with torch<=1.12 use c++14

**Comment by maxpain** [comment]
Any updates?

**Review by zhouzaida — APPROVED** [review]

**Comment by zhouzaida** [comment]
> Any updates?

Hi @maxpain , this PR has been merged.

**Comment by maxpain** [comment]
@zhouzaida When can we expect for a new version release?

**Comment by zhouzaida** [comment]
> @zhouzaida When can we expect for a new version to be released?

Hi, We will release the mmcv2.1.0 when the pytorch v2.1.0 releases.

**Comment by maxpain** [comment]
@zhouzaida when mmcv PyPi package with PyTorch 2.1.0 will be released so I can install it without building from source?

**Comment by zhouzaida** [comment]
> @zhouzaida when the mmcv PyPi package with PyTorch 2.1.0 will be released so I can install it without building from source?

We will provide these pre-built packages tomorrow.

**Comment by maxpain** [comment]
@zhouzaida any updates?

**Comment by zhouzaida** [comment]
Hi @maxpain, mmcv has released pre-built packages for torch2.1.0. Please install it with the following commands.

```bash
pip install -U openmim
mim install mmcv
```

**Pull request merged**
