### PR TITLE
Add type hints for mmcv/ops

### PR DESCRIPTION
**Pull request by ShawnHXH**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Add type hints in mmcv/ops/carafe.py, corner_pool.py and diff_iou_rotated.py.

## Modification

Add type hints in mmcv/ops/carafe.py, corner_pool.py and diff_iou_rotated.py.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by zhouzaida** [comment]
Hi, we can add type hints for several files at one time.

**Comment by ShawnHXH** [comment]
> Hi, we can add type hints for several files at one time.

I am sorry, sure.

**Comment by zhouzaida** [comment]
Hi, we also need to add type hints for other methods in mmcv/ops/carafe.py and mmcv/ops/corner_pool.py.

**Comment by ShawnHXH** [comment]
> Hi, we also need to add type hints for other methods in mmcv/ops/carafe.py and mmcv/ops/corner_pool.py.

Okay, the change has been made, please have a review.

**Comment by imabackstabber** [comment]
> > Hi, we also need to add type hints for other methods in mmcv/ops/carafe.py and mmcv/ops/corner_pool.py.
> 
> Okay, the change has been made, please have a review.

Thanks for your contribution.It will be better if `symbolic` method can be added with type hint too.

**Comment by ShawnHXH** [comment]
Hi, the type hints for `symbolic` method has been added.

**Review by zhouzaida — APPROVED** [review]

**Review by teamwong111 — APPROVED** [review]

**Pull request merged**
