### PR TITLE
[Fix] Remove dumplicate files in csrc

### PR DESCRIPTION
**Pull request by zhouzaida**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Remove some duplicate files in `mmcv/ops/csrc`.

## Modification

Remove some duplicate files in `mmcv/ops/csrc`.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repos?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

1. Pre-commit or other linting tools are used to fix the potential lint issues.
2. The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
3. If the modification has potential influence on downstream projects, this PR should be tested with downstream projects, like MMDet or MMCls.
4. The documentation has been modified accordingly, like docstring or example tutorials.

### CODE REVIEW

**Review by grimoire — APPROVED** [review]
LGTM

**Review by hellock — APPROVED** [review]

**Comment by hellock** [comment]
Why are `pytorch_cuda_helper.hpp` and `parrots_cuda_helper.hpp` placed in `csrc/common` instead of `csrc/pytorch` and `csrc/parrots`?

**Comment by zhouzaida** [comment]
> Why are `pytorch_cuda_helper.hpp` and `parrots_cuda_helper.hpp` placed in `csrc/common` instead of `csrc/pytorch` and `csrc/parrots`?

Files in `common/cuda` will include `pytorch_cuda_helper.hpp` and `parrots_cuda_helper.hpp` so putting them in `csrc/common` maybe more suitable 

https://github.com/open-mmlab/mmcv/blob/259ea5f63fb42c612331589bb66c539ac9df5fe4/mmcv/ops/csrc/common/cuda/bbox_overlaps_cuda_kernel.cuh#L5-L9

**Comment by hellock** [comment]
I see. LGTM now.

**Pull request merged**
