### PR TITLE
[Fix] Fix the bug of momentum updater with warmup policy

### PR DESCRIPTION
**Pull request by imyhxy**
## Motivation

The `MomemtumUpdaterHook` use two different field to store the regular_momentum: `regular_mom` and `regular_momentum`, and the `regular_momentum` never get real value into it which makes the `constant` warmup policy never get run.

## Details

`self.regular_mom` is initialized by `before_train_epoch` or `before_train_iter`, but in `_get_warmup_momentum`, it ignores the `regular_momentum` in the parameter list, and then tries to use `self.regular_momentum` in the constant policy and `self.regular_mom` in the linear and exp policy. `self.regular_momentum` is always an empty list, and constant policy will also return an empty list which will be passed by `_set_momentum`.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by teamwong111 — COMMENTED** [review]
LGTM. It would be great if you could help us with additional unit tests.

**Comment by imyhxy** [comment]
Great, I would add some unit tests later today.

**Comment by imyhxy** [comment]
@teamwong111 Hi, sorry for the long day. But I just curious that the process of momentum warmup is going from greeter one to smaller one? Any paper to propose that? Thanks.

**Comment by zhouzaida** [comment]
> 

No, the process of warmup will enlarger the regular momentum to get the warmup momentum.
`warmup_momentum = regulre_momentum / k`, k increases as the iteration increases.

It ensures that `warmup_momentum_{t}` is greather than `regulre_momentum_{t}` but not that `warmup_momentum_{t}` is greater than warmup_momentum_{t-1}`.

**Comment by zhouzaida** [comment]
Thank you very much for your contribution! We missed the warm up related unit tests. You can add those unit tests at [this file](https://github.com/open-mmlab/mmcv/blob/master/tests/test_runner/test_hooks.p).

**Comment by imyhxy** [comment]
@zhouzaida Unit tests were added. I just curious that why the momentum warmup is different from the learning rate. As the `warmup_lr_{t}` is always smaller than `regular_lr_{t}`.

**Comment by zhouzaida** [comment]
> @zhouzaida Unit tests were added. I just curious that why the momentum warmup is different from the learning rate. As the `warmup_lr_{t}` is always smaller than `regular_lr_{t}`.

https://fastai1.fast.ai/callbacks.one_cycle.html

**Review by zhouzaida — APPROVED** [review]

**Review by HAOCHENYE — APPROVED** [review]
LGTM.

**Pull request merged**
