### PR TITLE
[Fix] Remove warnings in compilation

### PR DESCRIPTION
**Pull request by teamwong111**
## Motivation

Remove warnings in compilation.
Remove 
    ```C++
    warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        for (size_t i = 0; i < embedding_dim; i++) {
                           ~~^~~~~~~~~~~~~~~
    ```

## Modification

As above.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by zhouzaida** [comment]
It would be better to provide the compilation log of the PR.

**Comment by zhouzaida** [comment]
Please resolve conflicts.

**Comment by teamwong111** [comment]
> Please resolve conflicts.

Done

**Review by grimoire — APPROVED** [review]
LGTM

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
