### PR TITLE
[Docs] Correct mistakes of examples

### PR DESCRIPTION
**Pull request by Happylkx**
## Modification

Renamed wrong variables 'f' to 'buffer'.

### CODE REVIEW

**Comment by zhouzaida** [comment]
> [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2120) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2120) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2120) it.

Hi, thanks for your contribution. Please sign the CLA.

**Comment by Happylkx** [comment]
> Read the Docs build failed!

CLA signed.

**Comment by Happylkx** [comment]
> > [CLA assistant check](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2120) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/open-mmlab/mmcv?pullRequest=2120) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/open-mmlab/mmcv?pullRequest=2120) it.
> 
> Hi, thanks for your contribution. Please sign the CLA.

CLA signed.

**Review by zhouzaida — APPROVED** [review]

**Comment by OpenMMLab-Assistant005** [comment]
Hi @Happylkx ！First of all, we want to express our gratitude for your significant PR in the MMDet project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution❤

**Pull request merged**
