### PR TITLE
Bump version to v1.3.0

### PR DESCRIPTION
**Pull request by zhouzaida**

### CODE REVIEW

**Comment by ycxioooong** [comment]
@zhouzaida Please sign the Contributor License Agreement.

**Comment by zhouzaida** [comment]
> @zhouzaida Please sign the Contributor License Agreement.

**Review by ycxioooong — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Suggest waiting for the refactoring about module initialization.

**Comment by zhouzaida** [comment]
> Suggest waiting for the refactoring about module initialization.



> Suggest waiting for the refactoring about module initialization.

OK

**Comment by ZwwWayne** [comment]
A kind reminder. If the pre-build mmcv support more versions, e.g., Pytorch 1.8 and CUDA 11, we may also update the table in the [README.md](https://github.com/open-mmlab/mmcv/blob/master/README.md)

**Comment by zhouzaida** [comment]
> A kind reminder: If the pre-build mmcv support more versions, e.g., Pytorch 1.8 and CUDA 11, we may also update the table in the [README.md](https://github.com/open-mmlab/mmcv/blob/master/README.md)

yep.

**Pull request closed without merging**
