### PR TITLE
Support Parrots extension for op ChamferDistance

### PR DESCRIPTION
**Pull request by CokeDong**
Support Parrots extension for op ChamferDistance

- Adaptation from #1933

### CODE REVIEW

**Review by luopeichao — APPROVED** [review]
LGTM

**Review by grimoire — APPROVED** [review]
LGTM

**Comment by ZwwWayne** [comment]
Hi @CokeDong,
Thanks for your kind contribution. Would you like to fix the lint issue so that we could merge this PR?
The details can be found by clicking the item of lint check as shown below
image

**Review by zhouzaida — APPROVED** [review]

**Comment by OpenMMLab-Team** [comment]
Hi @CokeDong ！First of all, we want to express our gratitude for your significant PR in the MMCV project. Your contribution is highly appreciated, and we are grateful for your efforts in helping improve this open-source project during your personal time. We believe that many developers will benefit from your PR.

We would also like to invite you to join our Special Interest Group (SIG) private channel on Discord, where you can share your experiences, ideas, and build connections with like-minded peers. To join the SIG channel, simply message moderator— OpenMMLab on Discord or briefly share your open-source contributions in the #introductions channel and we will assist you. Look forward to seeing you there! Join us ：https://discord.gg/UjgXkPWNqA

If you have WeChat account，welcome to join our community on WeChat. You can add our assistant ：openmmlabwx. Please add "mmsig + Github ID" as a remark when adding friends：）
Thank you again for your contribution！❤

**Pull request merged**
