### PR TITLE
[Fix] Remove unused header files

### PR DESCRIPTION
**Pull request by zhouzaida**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Resolves: #1582 
Remove unused header files in `mmcv/ops/csrc/pytorch/cuda/psamask_cuda.cu`

## Modification

- mmcv/ops/csrc/pytorch/cuda/psamask_cuda.cu

## BC-breaking (Optional)

**Linux**

Compiled successfully on all supported versions of PyTorch and CUDA.

TODO: Test on the following versions

- [ ] torch1.5-cuda10.1
- [ ] torch1.6-cuda10.1
- [ ] torch1.7-cuda10.2
- [x] torch1.8-cuda11.1
- [x] torch1.10.1-cuda11.1

**Windows**

Compiled successfully on all supported versions of PyTorch and CUDA and tested successfully on the following versions.

- [x] torch1.5-cuda10.1
- [x] torch1.6-cuda10.1
- [x] torch1.7-cuda10.2
- [x] torch1.8-cuda10.2
- [x] torch1.9-cuda11.1
- [x] torch1.10-cuda11.1
- [x]  torch1.10.2-cuda10.2

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [x] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [x] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by jinfagang** [comment]
Please merge this ASAP, currently all decent pytorch failed to build mmcv even from master source.

**Comment by grimoire** [comment]
MDcn test failed with torch1.10.
ms_deformable_attn failed cause oom, better test on devices with larger memory.

**Comment by an99990** [comment]
please merge this, as it is blocking packages like mmcv to be built and mmsegmentation

**Comment by zhouzaida** [comment]
> please merge this, as it is blocking packages like mmcv to be built and mmsegmentation

Got it. We are verifying the PR in all supported PyTorch and CUDA versions.

**Review by grimoire — APPROVED** [review]
tested on linux
- [x] torch1.10-cuda11.3
- [x] torch1.12-nightly-cuda11.3

**Comment by teamwong111** [comment]
tested on linux
- [x] torch1.5.0-cuda9.0

**Review by teamwong111 — APPROVED** [review]

**Pull request merged**
