### PR TITLE
[Fix] Fix bug of lr updater hook

### PR DESCRIPTION
**Pull request by zhouzaida**
Fix bug of https://github.com/open-mmlab/mmcv/issues/887

**[Next PR]**
I will do more unittest in https://github.com/open-mmlab/mmcv/blob/master/tests/test_runner/test_hooks.py.
But, maybe we should refactor the code `test_hooks.py` to make the test logic clearer.

```
├── test_basemodule.py
├── test_checkpoint.py
├── test_dist_utils.py
├── test_fp16.py
├── test_hooks.py
├── test_optimizer.py
├── test_runner.py
└── test_utils.py
```
to
```
├── test_basemodule.py
├── test_checkpoint.py
├── test_dist_utils.py
├── test_fp16.py
├── test_hooks
│   ├── test_checkpoint_hook.py
│   └── test_lr_updater_hook.py
├── test_hooks.py
├── test_optimizer.py
├── test_runner.py
└── test_utils.py
```

### CODE REVIEW

**Comment by hellock** [comment]
ping @nbei

**Review by nbei — COMMENTED** [review]
Could this pr contain the unit test for the modified parts?

**Comment by zhouzaida** [comment]
> Could this pr contain the unit test for the modified parts?

OK

**Review by ZwwWayne — APPROVED** [review]

**Comment by ZwwWayne** [comment]
Agree to refactor the test_hooks directory. The test_hooks.py can also be moved into test_hooks/ directory.

**Comment by zhouzaida** [comment]
> Agree to refactor the test_hooks directory. The test_hooks.py can also be moved into test_hooks/ directory.

Got it, I will refactor the unit test of hooks in the next PR.

**Pull request merged**
