### PR TITLE
Support pickle.loads (#499)

### PR DESCRIPTION
**Pull request by loveunk**

### CODE REVIEW

**Comment by xvjiarui** [comment]
Hi @loveunk 
Thanks for your contribution. 
Please add more comments to elaborate on this PR. And we may also add unittest for pickle.loads.

**Comment by loveunk** [comment]
Hi @xvjiarui , thank you for your comments.

This PR tries to solve one `pickle.loads()` issue as described in #499 .

It looks like the `mmcv.Config` object cannot be restored correctly by `pickle` in current mmcv implementation.

https://github.com/open-mmlab/mmcv/blob/7b18b97791167556643ed04ea8354f19c6306044/mmcv/utils/config.py#L356-L357

In `pickle.loads`, it tries to query `__setstate__` of the `mmcv.Config` instance, and not found. Then the query is captured by `__getattr__`.

However, in `getattr(self._cfg_dict, name)`, `self._cfg_dict` does not exist because the `__init__()` is not called when unpickling an instance.
Then `_cfg_dict` is queried with `__getattr__`. A recursion occurs.

**Comment by xvjiarui** [comment]
Hi @loveunk 
Sorry for the late reply. 
You may add unittest for this.

**Comment by loveunk** [comment]
> Hi @loveunk
> Sorry for the late reply.
> You may add unittest for this.

@xvjiarui Sure, I will commit some unit tests later. BTW, I am not familiar with the unit tests for mmcv. Is there any help documents to follow?

**Comment by xvjiarui** [comment]
Hi @loveunk 
You may check [this](https://github.com/open-mmlab/mmcv/blob/master/tests/test_config.py) file to have an understanding of unittest.

**Comment by loveunk** [comment]
@xvjiarui Thanks for your help. I have committed a new unittest.

**Comment by xvjiarui** [comment]
Thx! LGTM

**Review by xvjiarui — APPROVED** [review]

**Pull request merged**
