### PR TITLE
[Feature] Support CARAFE with Cambricon MLU backend

### PR DESCRIPTION
**Pull request by zcyKTH**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

The motivation of the PR is to support running CARAFE with Cambricon MLU backend.

It includes three parts:

Add `carafe_mlu_kernel.mlu` src code as MLU kernel.
Add `carafe_mlu.cpp` to support launching kernel in PyTorch.
Refactor `test_carafe.py` to support allclose check.

## Modification

MLU src code
Add MLU src code of CARAFE in directory `mmcv/ops/csrc/common/mlu/carafe_mlu_kernel.mlu`.
PyTorch adaptation
Adapt CARAFE for PyTorch in `mmcv/ops/csrc/pytorch/mlu/carefe_mlu.cpp`.
Common functions
Add IO functions with 2D/3D pattern in `mmcv/ops/csrc/common/mlu/common_mlu_helper.hpp`.
Unit test
Add baseline in `tests/data/for_carafe` and support test CARAFE with various backends in `tests/test_ops/test_carafe.py`.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [x] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [x] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [x] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [x] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Comment by grimoire** [comment]
Please update the unit test.

**Comment by zcyKTH** [comment]
> 

Done

**Review by grimoire — APPROVED** [review]
LGTM after update [docs/en/understand_mmcv/ops.md](https://github.com/open-mmlab/mmcv/blob/master/docs/en/understand_mmcv/ops.md) and  [docs/zh_cn/understand_mmcv/ops.md](https://github.com/open-mmlab/mmcv/blob/master/docs/zh_cn/understand_mmcv/ops.md)

**Comment by zhouzaida** [comment]
closed by #2212

**Pull request closed without merging**
