### PR TITLE
Implement corner pool with python for torch<1.5

### PR DESCRIPTION
**Pull request by grimoire**
## Motivation

Corner pool did not have it's own cuda kernel. This PR replace the cpp implementation with a python implementation.

## Modification

Remove code of corner pool in ops/csrc (both pytorch and parrots).
Add python implementation in `corner_pool.py`.

Has not tested on parrots.

### CODE REVIEW

**Comment by grimoire** [comment]
Note that since MMCV requires pytorch>=1.5.0. What if parrots provide support of  `torch.cummax`, we can remove all these codes and make it much cleaner.

**Comment by grimoire** [comment]
@zhouzaida benchmark might not be necessary since the python implementation is exactly the same as the c++ one(this ops has no cuda kernel). And the implementation is only triggered when torch<1.5, which is not supported now.

**Comment by zhouzaida** [comment]
> @zhouzaida benchmark might not be necessary since the python implementation is exactly the same as the c++ one(this ops has no cuda kernel). And the implementation is only triggered when torch<1.5, which is not supported now.

got it

**Review by luopeichao — APPROVED** [review]
It is passed in parrots. We will add torch.cummax in parrots in the future.

**Review by ZwwWayne — APPROVED** [review]

**Pull request merged**
