### PR TITLE
prevent from hangning in cv2.imshow()/cv2.waitkey

### PR DESCRIPTION
**Pull request by korabelnikov**
case:
Window has been closed after cv2.imshow; cv2.waitKey;
expected behavior:
- continue program
actual  behavior:
- program hangs

This PR fixes it

### CODE REVIEW

**Comment by hellock** [comment]
Thanks for the fix! There are some minor linting errors.

**Comment by korabelnikov** [comment]
oh, sorry! i've fixed

**Comment by korabelnikov** [comment]
@hellock i can't realize what is wrong with code coverage :(

**Comment by hellock** [comment]
> @hellock i can't realize what is wrong with code coverage :(

Don't worry. The coverage tests fail because no unit test covers the newly added codes.

**Pull request merged**
