### PR TITLE
fix roi align symbolic for torch>1.13

### PR DESCRIPTION
**Pull request by grimoire**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

Torch>=1.13 would not wrap Graph into GraphContext, so we can not reuse some tools in `torch.onnx`.

## Modification

Update roi_align symbolic.

## BC-breaking (Optional)

Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with this PR.

## Use cases (Optional)

If this PR introduces a new feature, it is better to list some use cases here, and update the documentation.

## Checklist

**Before PR**:

- [ ] I have read and followed the workflow indicated in the [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) to create this PR.
- [ ] Pre-commit or linting tools indicated in [CONTRIBUTING.md](https://github.com/open-mmlab/mmcv/blob/master/CONTRIBUTING.md) are used to fix the potential lint issues.
- [ ] Bug fixes are covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] New functionalities are covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, including docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with some of those projects, like MMDet or MMCls.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

### CODE REVIEW

**Review by zhouzaida — APPROVED** [review]

**Comment by smatrix017** [comment]
I see this has been merged to [open-mmlab:2.x](https://github.com/open-mmlab/mmcv/tree/2.x) branch, is there any timeline to fix for 1.x version?

**Comment by zhouzaida** [comment]
> I see this has been merged to [open-mmlab:2.x](https://github.com/open-mmlab/mmcv/tree/2.x) branch, is there any timeline to fix for mmcv 1.x versions?

Hi @smatrix017 , we will pick this commit to mmcv1.x this month.

**Comment by smatrix017** [comment]
Hi @zhouzaida, Thanks for the response. I am trying the rc 2.x mmcv version and getting following error while onyx conversion:

`torch.onnx.errors.CheckerError: Unrecognized attribute: axes for operator Squeeze

==> Context: Bad node spec for node. Name: /roi_extractor/extractor/roi_layers.0/Squeeze OpType: Squeeze`

Any idea what is going wrong here? 

I was getting the same error when I applied the changes in this PR to mmcv version 1.7 as well.

**Comment by buzuyun** [comment]
@smatrix017 Hi, I've encountered a same issue in the environment with `mmcv-full=1.7.2` and `torch=1.13.1`. Have you managed to resolve it? If so, any guidance you could provide would be greatly appreciated. Thank you in advance for your help!

**Pull request merged**
