### PR TITLE
[Enhancement] Optimize bbox overlap

### PR DESCRIPTION
**Pull request by grimoire**
## Motivation

This PR optmize bbox overlap ops.

## Modification

Add fast fp16 support and cpu implementation (pure python).
Note that new fp16 kernel is only tested on 2070s. Please do more test on other devices.

### CODE REVIEW

**Review by teamwong111 — APPROVED** [review]
LGTM. Whether to consider using pure PyTorch implementation to replace CUDA and other implementations?

**Comment by hellock** [comment]
Please add some benchmark results in the PR description.

**Comment by grimoire** [comment]
@teamwong111 I think this is a good idea since mmdetection are using their own [bbox_overlaps](https://github.com/open-mmlab/mmdetection/blob/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/mmdet/core/bbox/iou_calculators/iou2d_calculator.py#L75)(which is pure pytorch) instead of this one. 
And the optimization of this ops would not provide much help if it is not the bottleneck of training or inference.
Could we use pytorch implementation instead? @hellock

**Comment by ZwwWayne** [comment]
We'd better to leave benchmark results here, including their speed and memory comparison. Sometimes it will become speed and memory bottleneck when there are many GT bounding boxes. We should be sure in this PR that we make the right decision

**Comment by grimoire** [comment]
Test env:
- System: Ubuntu 18.04
- PyTorch: 1.8.1
- Device: 1660Ti
- CUDA toolkit: 11.3
- Nvidia Driver: 470.103.01

Test is performed on two inputs configs(limited by memory size of 1660Ti):
1. bbox0: [1e4, 4], bbox1: [1e4, 4]
2. bbox0: [1e6, 4], bbox1: [100, 4]
If  `aligned==True`，bbox1=bbox0.

speed test is performed with the script:

```python
        start.record()
        for _ in range(num_test):
            output = model(*inputs)
        end.record()
        torch.cuda.synchronize()

        print(
            f'{prefix} take time: {float(start.elapsed_time(end))/num_test:.5f}ms'
        )
```

```
bbox sizes: 1e6, 100

# origin (e36332e)
est mode:iou, aligned:True, prec:torch.float32 take time: 0.08735ms
Test mode:iou, aligned:True, prec:torch.float16 take time: 0.12835ms
Test mode:iou, aligned:False, prec:torch.float32 take time: 6.20847ms
Test mode:iou, aligned:False, prec:torch.float16 take time: 7.54264ms
Test mode:iof, aligned:True, prec:torch.float32 take time: 0.12685ms
Test mode:iof, aligned:True, prec:torch.float16 take time: 0.08870ms
Test mode:iof, aligned:False, prec:torch.float32 take time: 6.11029ms
Test mode:iof, aligned:False, prec:torch.float16 take time: 6.66254ms

# python (8e43d02)
Test mode:iou, aligned:True, prec:torch.float32 take time: 0.09253ms
Test mode:iou, aligned:True, prec:torch.float16 take time: 0.12445ms
Test mode:iou, aligned:False, prec:torch.float32 take time: 6.20700ms
Test mode:iou, aligned:False, prec:torch.float16 take time: 7.55791ms
Test mode:iof, aligned:True, prec:torch.float32 take time: 0.12671ms
Test mode:iof, aligned:True, prec:torch.float16 take time: 0.09965ms
Test mode:iof, aligned:False, prec:torch.float32 take time: 6.10923ms
Test mode:iof, aligned:False, prec:torch.float16 take time: 6.67853ms

bbox sizes: 1e4, 1e4

# origin (e36332e)
Test mode:iou, aligned:True, prec:torch.float32 take time: 0.01711ms
Test mode:iou, aligned:True, prec:torch.float16 take time: 0.01684ms
Test mode:iou, aligned:False, prec:torch.float32 take time: 6.20213ms
Test mode:iou, aligned:False, prec:torch.float16 take time: 7.26846ms
Test mode:iof, aligned:True, prec:torch.float32 take time: 0.01688ms
Test mode:iof, aligned:True, prec:torch.float16 take time: 0.01774ms
Test mode:iof, aligned:False, prec:torch.float32 take time: 6.14297ms
Test mode:iof, aligned:False, prec:torch.float16 take time: 7.07091ms

# python (8e43d02)
Test mode:iou, aligned:True, prec:torch.float32 take time: 0.09253ms
Test mode:iou, aligned:True, prec:torch.float16 take time: 0.12445ms
Test mode:iou, aligned:False, prec:torch.float32 take time: 6.20700ms
Test mode:iou, aligned:False, prec:torch.float16 take time: 7.55791ms
Test mode:iof, aligned:True, prec:torch.float32 take time: 0.12671ms
Test mode:iof, aligned:True, prec:torch.float16 take time: 0.09965ms
Test mode:iof, aligned:False, prec:torch.float32 take time: 6.10923ms
Test mode:iof, aligned:False, prec:torch.float16 take time: 6.67853ms


```

For memory usage, the test is performed with the help of `torch.autograd.profiler`. The max memory usage is 320Mb for both case on `aligned==True, prec==torch.float32`. I guess it is some kind of memory pool size.

It is strange that the performance is a little bit different from what I tested in 2070s, guess it is because 1660ti does not have TensorCore .

**Comment by ZwwWayne** [comment]
> 

So is the conclusion in 1660Ti consistent with that in 2070s?

**Comment by grimoire** [comment]
Nope, need more test.

**Comment by ZwwWayne** [comment]
It seems that the optimized version is more efficient and robust than the pure PyTorch implementation. I suggest using the optimized version rather than the pure PyTorch implementation. MMDet will plan to migrate to use the optimized CPU/CUDA implementation.

**Review by ZwwWayne — APPROVED** [review]

**Comment by ZwwWayne** [comment]
1. Can we add comments in the updated codes to indicate the acceleration rate?
2. Just to double-check, it seems that this PR uses pure PyTorch implementation in CPU mode, does this affect the speed?

**Comment by grimoire** [comment]
> 1. Can we add comments in the updated codes to indicate the acceleration rate?
> 2. Just to double-check, it seems that this PR uses pure PyTorch implementation in CPU mode, does this affect the speed?

We do not have a cpu implementation before, neither PyTorch or c++. I guess it is not that fast, but it is better than nothing.

**Pull request merged**
